dist: trusty
sudo: required
group: edge
branches:
  only:
  - v2
language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build-travis
notifications:
  email: false